language: python

python:
  - "2.7_with_system_site_packages"

# Installing packages with apt-get is much faster than with pip.
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-numpy python-scipy python-matplotlib

install:
  - pip install setuptools pillow
  - python setup.py develop

script:
  - cd xy_python_utils; python -m unittest discover -p "*_test.py"
